---
 # Hashicorp boxes are used by default as per vms.yaml, but there are options
 # for other boxes in the boxes.yaml file.
 #
ssh:
  insert_key: false

vms:
  #======================================#
  # Puppet Master machine                #
  #======================================#
  - name: "master.inf.puppet.vm"
    box: "master-virtualbox-v005"
    roles: [ "master" ]

  #======================================#
  # General-purpose machines, Portland   #
  #======================================#
  - name: "centos6a.pdx.puppet.vm"
    box: "puppetlabs/centos-6.6-64-nocm"
    roles: [ "posix_agent" ]

  - name: "centos7a.pdx.puppet.vm"
    box: "puppetlabs/centos-7.2-64-nocm"
    roles: [ "posix_agent" ]

  - name: "ubuntu1404a.pdx.puppet.vm"
    box: "puppetlabs/ubuntu-14.04-64-nocm"
    roles: [ "posix_agent" ]

  - name: "server2012r2a.pdx.puppet.vm"
    box: "win2012r2_1.0.4"
    roles: [ "windows_agent" ]

  - name: "server2016a.pdx.puppet.vm"
    box: "win2016_1.0.4"
    roles: [ "windows_agent" ]
